### ISSUE TITLE
WPF Guess Number 

### ISSUE THREAD

**Issue by Msvansn-143** [Msvansn-143/GuessNumber#2]
Developing WPF Guess Number Project Code Logic.

**Comment by SagarChandra07** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
I put the necessary dlls in the archive

**Comment by Msvansn-143** [comment]
Working on it
